<a href="https://colab.research.google.com/github/AlinaSabitova/Lab_AlinaSabitova/blob/main/%D0%94%D0%B71_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Worshop 2.1 Numpy
Скачайте этот ноутбук к себе.
Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
Сохраните результат в своём гитхаб репозитории.

# 1. Импортировать numpy и написать версию

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.23.5'

# 2.Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#3. Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((1,7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

#4. Создать вектор заполненный четными числами от 10 до 100

In [ ]:
arr = np.arange(10, 100)
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#5. Создать массив случайных чисел и развернуть его задом наперёд

In [31]:
arr = np.random.random(10)
print(arr)
arr[::-1]

[0.70069841 0.34377005 0.43933573 0.5300514  0.27477653 0.73059425
 0.65569905 0.75092853 0.0617207  0.39002615]


array([0.39002615, 0.0617207 , 0.75092853, 0.65569905, 0.73059425,
       0.27477653, 0.5300514 , 0.43933573, 0.34377005, 0.70069841])

#6. Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#7. Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
arr = np.eye(4, k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


#8. Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [11]:
arr = np.full((4,4), 7)
np.fill_diagonal(arr, [1,2,3,4])
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


In [4]:
arr = np.diag([1,2,3,4])
arr[arr == 0] = 7
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


#9. Создать матрицу размера 5 на 5 заполненную чиcлами от 0 до 4 в строках.

In [16]:
arr = np.zeros((5, 5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#10. Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [42]:
arr = np.random.randint(0, 100, (10, 10))
print(arr)
arr - arr.mean(axis = 1, keepdims=True)

[[52 26 78 23 48 62 12 49 12 24]
 [52 50 29 59 20 16 54 64 86 68]
 [70  5 88 65 88 34 14 84 11 54]
 [61 57 83 38 17 38 71 26 22 34]
 [82  3 57 92 59  3 84 24 61 69]
 [75 33 63  0 69 26 49 65 47 23]
 [62 71 41  3 44  3 58 57 41 54]
 [77 70 20 15 39 79 37 41  0 85]
 [ 1 88 86 84  8  9  0 86 22 69]
 [ 6 82  2 55 77 83 24 35 15 50]]


array([[ 13.4, -12.6,  39.4, -15.6,   9.4,  23.4, -26.6,  10.4, -26.6,
        -14.6],
       [  2.2,   0.2, -20.8,   9.2, -29.8, -33.8,   4.2,  14.2,  36.2,
         18.2],
       [ 18.7, -46.3,  36.7,  13.7,  36.7, -17.3, -37.3,  32.7, -40.3,
          2.7],
       [ 16.3,  12.3,  38.3,  -6.7, -27.7,  -6.7,  26.3, -18.7, -22.7,
        -10.7],
       [ 28.6, -50.4,   3.6,  38.6,   5.6, -50.4,  30.6, -29.4,   7.6,
         15.6],
       [ 30. , -12. ,  18. , -45. ,  24. , -19. ,   4. ,  20. ,   2. ,
        -22. ],
       [ 18.6,  27.6,  -2.4, -40.4,   0.6, -40.4,  14.6,  13.6,  -2.4,
         10.6],
       [ 30.7,  23.7, -26.3, -31.3,  -7.3,  32.7,  -9.3,  -5.3, -46.3,
         38.7],
       [-44.3,  42.7,  40.7,  38.7, -37.3, -36.3, -45.3,  40.7, -23.3,
         23.7],
       [-36.9,  39.1, -40.9,  12.1,  34.1,  40.1, -18.9,  -7.9, -27.9,
          7.1]])

#11. Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [55]:
arr = np.random.randint(0, 100, (10, 10))
print(arr)
print("Медиана:", np.median(arr, axis=0, keepdims=True))
arr - np.median(arr, axis=0, keepdims=True)

[[18 27 64 48 71 42 17 12 21 99]
 [23 41 99  1 45 64 67 81 26 22]
 [96 29 34 18 22 28  6  8 19 89]
 [77 47 26 54 62 23 65 74 96 22]
 [87 51 89 81 37 91 27 30 13 60]
 [17 64 29 95 11 64 64 81 48 57]
 [62  5 70 22 29 10 60 94 77 92]
 [84 61 68 60 64 26 21 26 25 65]
 [73 57 63 45 61 92 77 87 58 85]
 [32 47 92 82 51 33 54 88  9 63]]
Медиана: [[67.5 47.  66.  51.  48.  37.5 57.  77.5 25.5 64. ]]


array([[-49.5, -20. ,  -2. ,  -3. ,  23. ,   4.5, -40. , -65.5,  -4.5,
         35. ],
       [-44.5,  -6. ,  33. , -50. ,  -3. ,  26.5,  10. ,   3.5,   0.5,
        -42. ],
       [ 28.5, -18. , -32. , -33. , -26. ,  -9.5, -51. , -69.5,  -6.5,
         25. ],
       [  9.5,   0. , -40. ,   3. ,  14. , -14.5,   8. ,  -3.5,  70.5,
        -42. ],
       [ 19.5,   4. ,  23. ,  30. , -11. ,  53.5, -30. , -47.5, -12.5,
         -4. ],
       [-50.5,  17. , -37. ,  44. , -37. ,  26.5,   7. ,   3.5,  22.5,
         -7. ],
       [ -5.5, -42. ,   4. , -29. , -19. , -27.5,   3. ,  16.5,  51.5,
         28. ],
       [ 16.5,  14. ,   2. ,   9. ,  16. , -11.5, -36. , -51.5,  -0.5,
          1. ],
       [  5.5,  10. ,  -3. ,  -6. ,  13. ,  54.5,  20. ,   9.5,  32.5,
         21. ],
       [-35.5,   0. ,  26. ,  31. ,   3. ,  -4.5,  -3. ,  10.5, -16.5,
         -1. ]])

#12. Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.

#13. Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.

#14. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.