<a href="https://colab.research.google.com/github/AlinaSabitova/Lab_AlinaSabitova/blob/main/%D0%94%D0%B71_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Worshop 2.1 Numpy
Скачайте этот ноутбук к себе.
Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
Сохраните результат в своём гитхаб репозитории.

# 1. Импортировать numpy и написать версию

In [4]:
import numpy as np

In [6]:
np.__version__

'1.23.5'

# 2.Создать нулевой вектор размера 10

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#3. Создать вектор заполненный 7-ами размера 7

In [9]:
np.full((1,7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

#4. Создать вектор заполненный четными числами от 10 до 100

In [20]:
arr = np.arange(10, 100)
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#5. Создать массив случайных чисел и развернуть его задом наперёд

In [52]:
arr = np.random.random(10)
print(arr)
arr[::-1]

[0.59020941 0.28884691 0.88401793 0.21679722 0.49138139 0.84437766
 0.37082778 0.36500587 0.13292852 0.03223907]


array([0.03223907, 0.13292852, 0.36500587, 0.37082778, 0.84437766,
       0.49138139, 0.21679722, 0.88401793, 0.28884691, 0.59020941])

#6. Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [41]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#7. Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [44]:
arr = np.eye(4, k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


#8. Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [50]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [14]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#9. Создать матрицу размера 5 на 5 заполненную чиcлами от 0 до 4 в строках.

#10. Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

#11. Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [64]:
arr = np.random.randint(0, 100, (10, 10))
print(arr)
m = np.median(arr) # медиана
print(m)
arr -= m
print(arr)

[[35 26 81  0 33 20 98 71 63 53]
 [82 78  0 59 64 48 74 67 17 65]
 [41 28 49 37 82 99 44 19 52 99]
 [79 16 49 39  4 28 78 64 41 71]
 [74 66 36  2 48 64 98  8 12 71]
 [20  5 30 16 59 76 74  7 24 90]
 [ 3 77 81 26 18 86 83 36  8 82]
 [18  4 49 49 44 48 36 59 69 99]
 [72 65 22 11  0 40 27 28 17  8]
 [88  7  8 10 47 18 23 12 49  3]]
44.0


UFuncTypeError: ignored

In [65]:
my_array = np.array([1,2,3,4])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print("new_array:", new_array)

# Print `my_array` after appending
print("my_array after appending:", my_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]


#12. Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.

#13. Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу этого произведения.

#14. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.